### ISSUE TITLE
Unable to test on Windows

### ISSUE THREAD

**Issue by trajano** [DispatchMe/meteor-phantomjs-tests#1]
I am unable to run a simple test on Windows.  It just gets stuck at `----- RUNNING CLIENT TESTS -----`

Small sample with one test and the `meteor create` for the most part.

https://github.com/trajano/meteor-boilerplate/commit/4f463acc1f4dda0fd7b110a1f521f6ea6fcbd8a5

https://github.com/DispatchMe/meteor-phantomjs-tests/commit/3ea27c91aa9c532639b33099e012a25c00bc696e#diff-78c12f5adc1848d13b1c6f07055d996eR15

<pre>
1)  Uncaught error outside test suite:
   Uncaught TypeError: Object [object Object] has no method 'execFile'
    at startPhantom (packages/dispatch:phantomjs-tests/server.js:20:37)
    at Object.start (packages/dispatch:mocha-phantomjs/server.js:81:3)
    at nextSlot (packages/meteor/test_environment.js:34:1)
</pre>

**Comment by aldeed** [comment]
Seems execFile might work only with .exe files on Windows. Will accept a PR with a solution if there is one.

**Comment by trajano** [comment]
Are you passing in a script or something?  Not sure what to change in the code but if you need to run batch or cmd files you need to just call `cmd.exe /K scriptname.bat`

**Comment by aldeed** [comment]
Actually no, the error says `execFile` isn't even there. I think you should file this as a Meteor issue. Meteor is running tests differently on Windows, using a different version of Node perhaps. Not sure.

**Comment by trajano** [comment]
Ok from experimenting a bit.
`child_process` being returned at least on Windows is empty.
Not only that `require` being used is not the one provided by Node.  The one node provides has "cache" which this didn't have.

**Comment by trajano** [comment]
Anyway my hypothesis is that if I create a new package in Meteor that has `api.use('ecmascript')` or `api.use('modules')` 

I would expect that the `import childProcess from 'child_process'` would return `{}` at least on Windows.

**Comment by trajano** [comment]
OK I got it to work now.  Will create a PR.  I personally think it's an incomplete solution, rather I think we should use `meteor npm i phantomjs-prebuilt --save` rather than the `Npm.depends` but the solution so far works in Windows.

**Comment by aldeed** [comment]
@trajano, thanks. `dispatch:mocha-phantomjs@0.1.1` is published with this change

**Comment by trajano** [comment]
Now we just need to wait for https://github.com/mochajs/mocha/pull/2218
